#include "Ast.h"
#include <stack>
#include <string>
#include "IRBuilder.h"
#include "Instruction.h"
#include "SymbolTable.h"
#include "Type.h"
#include "Unit.h"
extern Unit unit;
extern MachineUnit mUnit;

#include <iostream>

extern FILE* yyout;
int Node::counter = 0;
IRBuilder* Node::builder;
Type *funcRetType = nullptr;
bool haveRet = false;

void Node::backPatch(std::vector<Instruction*>& list, BasicBlock* bb) {
    for (auto& inst : list) {
        if (inst->isCond())
            dynamic_cast<CondBrInstruction*>(inst)->setTrueBranch(bb);
        else if (inst->isUncond())
            dynamic_cast<UncondBrInstruction*>(inst)->setBranch(bb);
    }
}

std::vector<Instruction*> Node::merge(std::vector<Instruction*>& list1,
                                      std::vector<Instruction*>& list2) {
    std::vector<Instruction*> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit* unit) {
    IRBuilder* builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void FunctionDef::genCode() {
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    if(this->decl)
        decl->genCode();
    if(this->stmt)
        stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors
     * for each basic block. Todo
     */

    for(auto block=func->begin();block!=func->end();block++){
        // jmp only happen at the end of a block
        Instruction* ins_begin=(*block)->begin();
        Instruction* ins_end=(*block)->rbegin();

        //detele the wrong jump inst in the block
        while (ins_begin!=ins_end)
        {
            if(ins_begin->isCond()||ins_begin->isUncond()){
                (*block)->remove(ins_begin);
            }
            ins_begin=ins_begin->getNext();
        }
        if(ins_end->isCond()){
            //设置好truebranch和falsebranch
            BasicBlock* truebranch, *falsebranch;
            truebranch = dynamic_cast<CondBrInstruction*>(ins_end)->getTrueBranch();
            if(truebranch->empty()){
                if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::intType) {
                    new RetInstruction(new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0)),truebranch);
                } else if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::voidType) {
                    new RetInstruction(nullptr, truebranch);
                }
            }
            falsebranch = dynamic_cast<CondBrInstruction*>(ins_end)->getFalseBranch();
            if(falsebranch->empty()){
                if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::intType) {
                    new RetInstruction(new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0)),falsebranch);
                }else if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::voidType) {
                    new RetInstruction(nullptr, falsebranch);
                }
            }
            (*block)->addSucc(truebranch);
            (*block)->addSucc(falsebranch);
            truebranch->addPred((*block));
            falsebranch->addPred((*block));
        }
        else if(ins_end->isUncond()){
            BasicBlock* branch = dynamic_cast<UncondBrInstruction*>(ins_end)->getBranch();
            branch->addPred((*block));
            (*block)->addSucc(branch);

            if(branch->empty()){
                if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::intType) {
                    new RetInstruction(new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0)),branch);
                }else if ((dynamic_cast<FunctionType*>(se->getType()))->getRetType() == TypeSystem::voidType) {
                    new RetInstruction(nullptr, branch);
                }
            }
        }
        else if(!ins_end->isRet()){
            if (((FunctionType*)(se->getType()))->getRetType() == TypeSystem::voidType) {
                new RetInstruction(nullptr, *block);
            }
        }
    }
    //not finish
}

void BinaryExpr::genCode() {
    BasicBlock* bb = builder->getInsertBB();
    Function* func = bb->getParent();
    if (op == AND) {
        BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());

    } else if (op == OR) {
        // Todo
        BasicBlock *trueBB = new BasicBlock(func);
        expr1->genCode();
        backPatch(expr1->falseList(), trueBB);
        builder->setInsertBB(trueBB);
        expr2->genCode();
        true_list = merge(expr1->trueList(), expr2->trueList());
        false_list = expr2->falseList();
    } else if (op >= LESS && op <= NOTEQUAL) {
        // Todo
        expr1->genCode();
        expr2->genCode();
        Operand* src1 = expr1->getOperand();
        Operand* src2 = expr2->getOperand();
        if (src1->getType()->isBool()) {
            Operand* dst = new Operand(new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel()));
            new ZextInstruction(dst, src1, bb);
            src1 = dst;
        }
        if (src2->getType()->isBool()) {
            Operand* dst = new Operand(new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel()));
            new ZextInstruction(dst, src2, bb);
            src2 = dst;
        }

        int cmpOp = -1;
        switch (op) {
            case GREAT:
                cmpOp = CmpInstruction::G;
                break;
            case LESS:
                cmpOp = CmpInstruction::L;
                break;
            case GREATEQUAL:
                cmpOp = CmpInstruction::GE;
                break;
            case LESSEQUAL:
                cmpOp = CmpInstruction::LE;
                break;
            case EQUAL:
                cmpOp = CmpInstruction::E;
                break;
            case NOTEQUAL:
                cmpOp = CmpInstruction::NE;
                break;
        }
        new CmpInstruction(cmpOp, dst, src1, src2, bb);
        BasicBlock *truebranch, *falsebranch, *tempbranch;
        truebranch = new BasicBlock(func);
        falsebranch = new BasicBlock(func);
        tempbranch = new BasicBlock(func);
        true_list.push_back(new CondBrInstruction(truebranch, tempbranch, dst, bb));
        false_list.push_back(new UncondBrInstruction(falsebranch, tempbranch));

    } else if (op >= ADD && op <= MOD) {
        expr1->genCode();
        expr2->genCode();
        Operand* src1 = expr1->getOperand();
        Operand* src2 = expr2->getOperand();
        int opcode = -1;
        switch (op) {
            case ADD:
                opcode = BinaryInstruction::ADD;
                break;
            case SUB:
                opcode = BinaryInstruction::SUB;
                break;
            case MUL:
                opcode = BinaryInstruction::MUL;
                break;
            case DIV:
                opcode = BinaryInstruction::DIV;
                break;
            case MOD:
                opcode = BinaryInstruction::MOD;
                break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode() {
    // we don't need to generate code.
}

void Id::genCode() {
    BasicBlock* bb = builder->getInsertBB();
    Operand* addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();

    if (type->isInt())
        new LoadInstruction(dst, addr, bb);
    else if (type->isArray()) {
        //curr add is the add of a,we need to find the real add of a[][]
        if (arrayIndices) {
            Type* elementType = (dynamic_cast<ArrayType*>(this->type))->getElementType();
            Type* cur = this->type;
            ExprNode* arr = arrayIndices;

            Operand* _src = addr;
            Operand* _dst = dst;
            bool paramFirst = false;
            bool pointer = false;
            bool firstFlag = true;
            while (arr) {
                if (((ArrayType*)cur)->getLength() < 0) {
                    //load it
                    _src = new Operand(new TemporarySymbolEntry(new PointerType(elementType), SymbolTable::getLabel()));
                    new LoadInstruction(_src, addr, bb);
                    paramFirst = true;
                    firstFlag = false;
                }

                arr->genCode();
                auto gep = new GepInstruction(_dst, _src, arr->getOperand(), bb, paramFirst);
                if (!paramFirst && firstFlag) {
                    gep->setFirst();
                    firstFlag = false;
                }
                if (paramFirst)
                    paramFirst = false;

                if (elementType == TypeSystem::intType || elementType == TypeSystem::constIntType){
                    pointer = false;
                    break;
                }
                elementType = ((ArrayType*)elementType)->getElementType();
                cur = ((ArrayType*)cur)->getElementType();
                _src = _dst;
                _dst = new Operand(new TemporarySymbolEntry(new PointerType(elementType), SymbolTable::getLabel()));
                arr = (ExprNode*)(arr->getNext());

                if (!arr) {
                    Operand* idx = new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0));
                    new GepInstruction(_dst, _src, idx, bb);
                    pointer = true;
                    break;
                }
            }
            dst = _dst;
            //如果不是左值
            //取到地址后需要将数组内容load进入寄存器
            if (!left && !pointer) {
                Operand* temp = new Operand(new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel()));
                new LoadInstruction(temp, dst, bb);
                dst = temp;
            }

        } else {
            //只是一个数组指针的情况
            //is a pointer
            if (((ArrayType*)(this->type))->getLength() < 0) {
                Operand* temp = new Operand(new TemporarySymbolEntry(new PointerType(((ArrayType*)(this->type))->getElementType()), SymbolTable::getLabel()));
                new LoadInstruction(temp, addr, bb);
                dst = temp;
            } else {
                Operand* idx = new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0));
                auto gep = new GepInstruction(dst, addr, idx, bb);
                gep->setFirst();
            }
        }
    }
}

void DeclStmt::genCode() {
    IdentifierSymbolEntry* se = dynamic_cast<IdentifierSymbolEntry*>(id->getSymbolEntry());
    if (se->isGlobal()) {
        Operand* addr;
        SymbolEntry* addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
        unit.insertGlobal(se);
        //别忘了这个
        mUnit.insertGlobal(se);
    } else if (se->isLocal() || se->isParam()) {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        Operand *addr;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        
        Operand* paramAddr = nullptr;
        if(se->isParam())
            paramAddr = se->getAddr();
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.

        if (expr) {
            if (expr->isArrayInitList()) {
                //寻址初始化
                Operand* init = nullptr;
                BasicBlock* bb = builder->getInsertBB();
                ExprNode* temp = expr;
                std::stack<ExprNode*> stk;
                std::vector<int> idx;
                idx.push_back(0);
                while (temp) {
                    if (temp->isArrayInitList()) {
                        stk.push(temp);
                        idx.push_back(0);
                        temp = (dynamic_cast<ArrayInitList*>temp)->getExpr();
                        continue;
                    } else {
                        temp->genCode();
                        Type* type = (dynamic_cast<ArrayType*>(se->getType()))->getElementType();
                        Operand* _src = addr;
                        Operand* _dst;
                        Operand* index;
                        bool firstFlag = true;
                        int i = 1;
                        while (true) {
                            _dst = new Operand(new TemporarySymbolEntry(new PointerType(type), SymbolTable::getLabel()));
                            index = (new Constant(new ConstantSymbolEntry(TypeSystem::intType, idx[i++])))->getOperand();
                            auto gep = new GepInstruction(_dst, _src, index, bb);
                            gep->setInitOperand(init);
                            if (firstFlag) {
                                gep->setFirst();
                                firstFlag = false;
                            }
                            if (type == TypeSystem::intType || type == TypeSystem::constIntType){
                                gep->setLast();
                                init = _dst;
                                break;
                            }
                            type = ((ArrayType*)type)->getElementType();
                            _src = _dst;
                        }
                        new StoreInstruction(_dst, temp->getOperand(), bb);
                    }
                    while (true) {
                        if (temp->getNext()) {
                            temp = (ExprNode*)(temp->getNext());
                            idx[idx.size() - 1]++;
                            break;
                        } else {
                            temp = stk.top();
                            stk.pop();
                            idx.pop_back();
                            if (stk.empty())
                                break;
                        }
                    }
                    if (stk.empty())
                        break;
                }
            } else {
                BasicBlock* bb = builder->getInsertBB();
                expr->genCode();
                Operand* src = expr->getOperand();
                new StoreInstruction(addr, src, bb);
            }
        }
        if (se->isParam()) {
            BasicBlock* bb = builder->getInsertBB();
            new StoreInstruction(addr, paramAddr, bb);
        }
    }
    if (this->getNext()) {
        this->getNext()->genCode();
    }
}

void AssignStmt::genCode() {
    BasicBlock* bb = builder->getInsertBB();
    expr->genCode();
    Operand* addr = nullptr;
    if (lval->getTopType()->isInt())
        addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymbolEntry())->getAddr();
    else if (lval->getTopType()->isArray()) {
        ((Id*)lval)->setLeft();
        lval->genCode();
        addr = lval->getOperand();
    }
    Operand* src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just
     * store the result of the `expr` to the addr of the id. If you want to
     * implement array, you have to caculate the address first and then store
     * the result into it.
     */
    new StoreInstruction(addr, src, bb);
}


void IfStmt::genCode() {
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);

}

void IfElseStmt::genCode() {
    // Todo
    Function *func;
    BasicBlock *then_bb, *else_bb, *end_bb;
    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    else_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), else_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(else_bb);
    elseStmt->genCode();
    else_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, else_bb);

    builder->setInsertBB(end_bb);

}

void CompoundStmt::genCode() {
    // Todo
    if (stmt)
        stmt->genCode();
}

void SeqNode::genCode() {
    // Todo
    stmt1->genCode();
    stmt2->genCode();
}

void ReturnStmt::genCode() {
    BasicBlock* bb = builder->getInsertBB();
    Operand* src = nullptr;
    if (this->retValue) {
        this->retValue->genCode();
        src = this->retValue->getOperand();
    }
    new RetInstruction(src, bb);
}
void ExprStmt::genCode() {
    // Todo
    expr->genCode();
}
void ContinueStmt::genCode() {
    // Todo
    Function* func = builder->getInsertBB()->getParent();
    BasicBlock* bb = builder->getInsertBB();
    new UncondBrInstruction(((WhileStmt*)whileStmt)->get_cond_bb(), bb);
    BasicBlock* next_bb = new BasicBlock(func);
    builder->setInsertBB(next_bb);
}
void BreakStmt::genCode() {
    // Todo
    Function* func = builder->getInsertBB()->getParent();
    BasicBlock* bb = builder->getInsertBB();
    new UncondBrInstruction(((WhileStmt*)whileStmt)->get_end_bb(), bb);
    BasicBlock* next_bb = new BasicBlock(func);
    builder->setInsertBB(next_bb);
}
void WhileStmt::genCode() {
    Function* func = builder->getInsertBB()->getParent();
    BasicBlock *cond_bb=new BasicBlock(func), *while_bb=new BasicBlock(func), *end_bb=new BasicBlock(func), *bb=builder->getInsertBB();

    this->setCondBB(cond_bb);
    this->setEndBB(end_bb);
    new UncondBrInstruction(cond_bb, bb);
    builder->setInsertBB(cond_bb);
    this->cond->genCode();

    backPatch(cond->trueList(),while_bb);
    backPatch(cond->falseList(),end_bb);

    builder->setInsertBB(while_bb);
    this->stmt->genCode();
    while_bb = builder->getInsertBB();
    new UncondBrInstruction(cond_bb,while_bb);

    builder->setInsertBB(end_bb);

}

void ArrayInitList::genCode() {
    // Todo
}
void FuncExpr::genCode() {
    std::vector<Operand*> operands;
    ExprNode* paramTemp = param;
    while (paramTemp) {
        paramTemp->genCode();
        operands.push_back(paramTemp->getOperand());
        paramTemp = (ExprNode*)paramTemp->getNext();
    }
    BasicBlock* bb = builder->getInsertBB();
    new CallInstruction(dst, symbolEntry, operands, bb);

}
void UnaryExpr::genCode() {
    // Todo
    expr->genCode();
    BasicBlock* bb = builder->getInsertBB();
    Type* unaryExprType = expr->getType();
    Operand* src1, *src2;
    switch (op)
    {
    case SUB:
        src1 = new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0));
        if (unaryExprType->isBool()) {
            src2 = new Operand(new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel()));
            new ZextInstruction(src2, expr->getOperand(), bb);
        } else
            src2 = expr->getOperand();
        new BinaryInstruction(BinaryInstruction::SUB, dst, src1, src2, bb);
        break;
    case ADD:
        //如果取正？似乎不用完成
        fprintf(stderr,"not finish yet\n");
        break;
    case NOT:
        src1 = expr->getOperand();
        if (unaryExprType->getSize() == 32) {
            src2 = new Operand(new TemporarySymbolEntry(TypeSystem::boolType, SymbolTable::getLabel()));
            new CmpInstruction(CmpInstruction::NE, src2, src1,new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0)),bb);
            src1 = src2;
        }
        new XorInstruction(dst, src1, bb);
    }
}
void ExprNode::genCode() {
    // Todo
}

void Int2BoolExpr::genCode() {
    expr->genCode();
    BasicBlock* bb = builder->getInsertBB();
    Function* func = bb->getParent();
    BasicBlock* truebranch = new BasicBlock(func);
    BasicBlock* tempbranch = new BasicBlock(func);
    BasicBlock* falsebranch = new BasicBlock(func);
    Operand *zero = new Operand(new ConstantSymbolEntry(TypeSystem::intType, 0));
    new CmpInstruction(CmpInstruction::NE, dst, expr->getOperand(), zero, bb);
    Instruction* cond = new CondBrInstruction(truebranch, tempbranch, this->dst, bb);
    
    Instruction* uncond = new UncondBrInstruction(falsebranch, tempbranch);

    trueList().push_back(cond);
    falseList().push_back(uncond);
}

void ContinueStmt::typeCheck() {
    //在parse里检查
}
void BreakStmt::typeCheck() {
    //在parse里检查
}
void WhileStmt::typeCheck() {
    if (stmt)
        stmt->typeCheck();
}

void ArrayInitList::typeCheck() {

}
void FuncExpr::typeCheck() {
    
}
void UnaryExpr::typeCheck() {

}

void ExprStmt::typeCheck() {
   
}

void Ast::typeCheck() {
    if (root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck() {
    haveRet = false;

    SymbolEntry* se = this->getSymbolEntry();
    Type* ret = (dynamic_cast<FunctionType*>(se->getType()))->getRetType();
    funcRetType = ret;

    StmtNode* stmt = this->stmt;
    if (stmt == nullptr) {
        if (ret != TypeSystem::voidType){
            fprintf(stderr, "function does not return a vaild value\n");
            //assert(0);
            return;
        }
    }else
        stmt->typeCheck();

    if(!funcRetType->isVoid() && !haveRet){
        fprintf(stderr, "function \"%s\" shoule return a vaild type\n",this->se->toStr().c_str());
        //assert(0);
        return;
    }

}

void BinaryExpr::typeCheck() {
    if(this->expr1->getType()->isVoid() || this->expr2->getType()->isVoid()){
        fprintf(stderr, "void expr cannot in a BinaryExpr\n");
        assert(false);
    }
}

void Constant::typeCheck() {
    
}

void Id::typeCheck() {
    
}

void IfStmt::typeCheck() {
    if (thenStmt)
        thenStmt->typeCheck();
}

void IfElseStmt::typeCheck() {
    if (thenStmt)
        thenStmt->typeCheck();
    if (elseStmt)
        elseStmt->typeCheck();
}

void CompoundStmt::typeCheck() {
    if (stmt)
        stmt->typeCheck();
}

void SeqNode::typeCheck() {
    if (stmt1)
        stmt1->typeCheck();
    if (stmt2)
        stmt2->typeCheck();
}

void DeclStmt::typeCheck() {
    
}

void ReturnStmt::typeCheck() {
    Type *RetType = this->retValue->getSymbolEntry()->getType();
    if(!funcRetType)
        return;
    if(this->retValue){
        if(this->retValue->getType()->isArray()){
            return;
        }
    }
    if (!retValue && !funcRetType->isVoid()) {
        fprintf(stderr, "you should return %s, but return void\n", funcRetType->toStr().c_str());
        //assert(0);
    }
    if (retValue && funcRetType->isVoid()) {
        fprintf(stderr, "you should return void, but return %s\n",this->retValue->getSymbolEntry()->getType()->toStr().c_str());
        //assert(0);
    }

    if(!this->retValue && funcRetType->isVoid()){
        goto Out;
    }

    if(RetType->isFunc())
        RetType = dynamic_cast<FunctionType*>(RetType)->getRetType();

    if(this->retValue && RetType!=funcRetType){
        if((RetType->isInt() && funcRetType->isInt()))
            goto Out;
        if(this->retValue->getSymbolEntry()->getType()->isFunc())
            return;
        fprintf(stderr, "you should return:%s, but return %s\n",funcRetType->toStr().c_str(), this->retValue->getSymbolEntry()->getType()->toStr().c_str());
        //assert(0);
    }
Out:
    haveRet = true;

}

void AssignStmt::typeCheck() {
    
}

Type* Id::getType() {
    SymbolEntry* se = this->getSymbolEntry();
    if (!se)
        return TypeSystem::voidType;
    Type* type = se->getType();
    if (!arrayIndices)
        return type;
    else if (type->isArray()) {
        ArrayType* temp1 = (ArrayType*)type;
        ExprNode* temp2 = arrayIndices;
        while (!temp1->getElementType()->isInt()) {
            if (!temp2) {
                return temp1;
            }
            temp2  = (ExprNode*)(temp2->getNext());
            temp1 = (ArrayType*)(temp1->getElementType());
        }
        if (!temp2) {
            return temp1;
        }
    }
    return TypeSystem::intType;
}

void ExprNode::output(int level) {
    std::string name, type;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    fprintf(yyout, "%*cconst string\ttype:%s\t%s\n", level, ' ', type.c_str(), name.c_str());
}

void Ast::output() {
    fprintf(yyout, "program\n");
    if (root != nullptr)
        root->output(4);
}

void BinaryExpr::output(int level) {
    std::string op_str;
    switch (op) {
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case MUL:
            op_str = "mul";
            break;
        case DIV:
            op_str = "div";
            break;
        case MOD:
            op_str = "mod";
            break;
        case AND:
            op_str = "and";
            break;
        case OR:
            op_str = "or";
            break;
        case LESS:
            op_str = "less";
            break;
        case LESSEQUAL:
            op_str = "lessequal";
            break;
        case GREAT:
            op_str = "greater";
            break;
        case GREATEQUAL:
            op_str = "greaterequal";
            break;
        case EQUAL:
            op_str = "equal";
            break;
        case NOTEQUAL:
            op_str = "notequal";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\ttype: %s\n", level, ' ', op_str.c_str(), type->toStr().c_str());
    expr1->output(level + 4);
    expr2->output(level + 4);
}

BinaryExpr::BinaryExpr(SymbolEntry* se, int op, ExprNode* expr1, ExprNode* expr2): ExprNode(se), op(op), expr1(expr1), expr2(expr2) {
    dst = new Operand(se);
    std::string op_str;
    switch (op) {
        case ADD:
            op_str = "+";
            break;
        case SUB:
            op_str = "-";
            break;
        case MUL:
            op_str = "*";
            break;
        case DIV:
            op_str = "/";
            break;
        case MOD:
            op_str = "%";
            break;
        case AND:
            op_str = "&&";
            break;
        case OR:
            op_str = "||";
            break;
        case LESS:
            op_str = "<";
            break;
        case LESSEQUAL:
            op_str = "<=";
            break;
        case GREAT:
            op_str = ">";
            break;
        case GREATEQUAL:
            op_str = ">=";
            break;
        case EQUAL:
            op_str = "==";
            break;
        case NOTEQUAL:
            op_str = "!=";
            break;
    }

    //void cannot used in binaryNode
    if (expr1->getType()->isVoid() || expr2->getType()->isVoid()) {
        fprintf(stderr,"void cannot used in binaryNode %s\n", op_str.c_str());
    }
    if (op >= BinaryExpr::AND && op <= BinaryExpr::NOTEQUAL) {
        type = TypeSystem::boolType;
        if (op == BinaryExpr::AND || op == BinaryExpr::OR) {
            if (expr1->getType()->isInt() && expr1->getType()->getSize() == 32) {
                Int2BoolExpr* temp = new Int2BoolExpr(expr1);
                this->expr1 = temp;
            }
            if (expr2->getType()->isInt() && expr2->getType()->getSize() == 32) {
                Int2BoolExpr* temp = new Int2BoolExpr(expr2);
                this->expr2 = temp;
            }
        }
    } else
        type = TypeSystem::intType;
};


int BinaryExpr::getValue() {
    int value = 0;
    switch (op) {
        case ADD:
            value = expr1->getValue() + expr2->getValue();
            break;
        case SUB:
            value = expr1->getValue() - expr2->getValue();
            break;
        case MUL:
            value = expr1->getValue() * expr2->getValue();
            break;
        case DIV:
            if(expr2->getValue())
                value = expr1->getValue() / expr2->getValue();
            break;
        case MOD:
            value = expr1->getValue() % expr2->getValue();
            break;
        case AND:
            value = expr1->getValue() && expr2->getValue();
            break;
        case OR:
            value = expr1->getValue() || expr2->getValue();
            break;
        case LESS:
            value = expr1->getValue() < expr2->getValue();
            break;
        case LESSEQUAL:
            value = expr1->getValue() <= expr2->getValue();
            break;
        case GREAT:
            value = expr1->getValue() > expr2->getValue();
            break;
        case GREATEQUAL:
            value = expr1->getValue() >= expr2->getValue();
            break;
        case EQUAL:
            value = expr1->getValue() == expr2->getValue();
            break;
        case NOTEQUAL:
            value = expr1->getValue() != expr2->getValue();
            break;
    }
    return value;
}

UnaryExpr::UnaryExpr(SymbolEntry* se, int op, ExprNode* expr): ExprNode(se, UNARYEXPR), op(op), expr(expr) {
    std::string op_str;
    switch (op)
    {
    case SUB:
        op_str = "-";
    case NOT:
        op_str = "!";
        break;
    case ADD:
        op_str = "+";
    default:
        break;
    }
    dst = new Operand(se);
    type = TypeSystem::intType;

    if (expr->getType()->isVoid()) {
        fprintf(stderr,"invalid operand of type \'void\' to unary \'opeartor%s\'\n", op_str.c_str());
    }

    if (expr->isUnaryExpr()) {
            UnaryExpr* ue = (UnaryExpr*)expr;
            if (ue->getOp() == UnaryExpr::NOT && ue->getType() == TypeSystem::intType)
                ue->setType(TypeSystem::boolType);
    }
};

void UnaryExpr::output(int level) {
    std::string op_str;
    switch (op) {
        case NOT:
            op_str = "not";
            break;
        case SUB:
            op_str = "minus";
            break;
    }
    fprintf(yyout, "%*cUnaryExpr\top: %s\ttype: %s\n", level, ' ', op_str.c_str(), type->toStr().c_str());
    expr->output(level + 4);
}

int UnaryExpr::getValue() {
    int value = 0;
    switch (op) {
        case SUB:
            value = -(expr->getValue());
            break;
        case NOT:
            value = !(expr->getValue());
            break;
    }
    return value;
}

void FuncExpr::output(int level) {
    std::string name, type;
    int scope;
    if (symbolEntry) {
        name = symbolEntry->toStr();
        type = symbolEntry->getType()->toStr();
        scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
        fprintf(yyout, "%*cFuncExpr\tfunction name: %s\tscope: %d\ttype: %s\n", level, ' ', name.c_str(), scope, type.c_str());
        Node* temp = param;
        while (temp) {
            temp->output(level + 4);
            temp = temp->getNext();
        }
    }
}

void Constant::output(int level) {
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

int Constant::getValue() {
    return ((ConstantSymbolEntry*)symbolEntry)->getValue();
}

int Id::getValue() {
    return ((IdentifierSymbolEntry*)symbolEntry)->getValue();
}

void Id::output(int level) {
    std::string name, type;
    int scope;
    if (symbolEntry) {
        name = symbolEntry->toStr();
        type = symbolEntry->getType()->toStr();
        scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
        fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ', name.c_str(), scope, type.c_str());
        if (arrayIndices) {
            ExprNode* temp = arrayIndices;
            int i = 0;
            while (temp) {
                temp->output(level + 4 + 4 * i++);
                temp = (ExprNode*)(temp->getNext());
            }
        }
    }
}

void ArrayInitList::output(int level) {
    std::string type;
    if (symbolEntry->getType())
        type = symbolEntry->getType()->toStr();
    fprintf(yyout, "%*cArrayInitList\ttype: %s\n", level, ' ',
            type.c_str());
    Node* temp = expr;
    while (temp) {
        temp->output(level + 4);
        temp = temp->getNext();
    }
}

void ArrayInitList::addChildExpr(ExprNode* expr) {
    //增加子表达式
    childExprCount++;
    if (!this->expr) 
        this->expr = expr;
    else 
        this->expr->setNext(expr);
    
}

bool ArrayInitList::isFull() {
    ArrayType* type = (ArrayType*)(this->symbolEntry->getType());
    return childExprCount == type->getLength();
}

void ArrayInitList::paddingArray() {
    Type* elementType = ((ArrayType*)(this->getType()))->getElementType();
    if (elementType->isArray()) {
        while (!this->isFull())
            this->addChildExpr(new ArrayInitList(new ConstantSymbolEntry(elementType)));
        ExprNode* temp = this->expr;
        while (temp) {
            ((ArrayInitList*)temp)->paddingArray();
            temp = (ExprNode*)(temp->getNext());
        }
    }else if (elementType->isInt()) {
        while (!this->isFull())
            this->addChildExpr(new Constant(new ConstantSymbolEntry(elementType, 0)));
        return;
    }
}

void Int2BoolExpr::output(int level) {
    fprintf(yyout, "%*cImplictCastExpr\ttype: %s to %s\n", level, ' ', expr->getType()->toStr().c_str(), type->toStr().c_str());
    this->expr->output(level + 4);
}

void CompoundStmt::output(int level) {
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    if (stmt)
        stmt->output(level + 4);
}

void SeqNode::output(int level) {
    stmt1->output(level);
    stmt2->output(level);
}

void DeclStmt::output(int level) {
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    id->output(level + 4);
    if (expr)
        expr->output(level + 4);
    if (this->getNext()) {
        this->getNext()->output(level);
    }
}

void IfStmt::output(int level) {
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level) {
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void WhileStmt::output(int level) {
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    cond->output(level + 4);
    stmt->output(level + 4);
}
void BreakStmt::output(int level) {
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}

void ContinueStmt::output(int level) {
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void ReturnStmt::output(int level) {
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    if (retValue != nullptr)
        retValue->output(level + 4);
}

void AssignStmt::output(int level) {
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void ExprStmt::output(int level) {
    fprintf(yyout, "%*cExprStmt\n", level, ' ');
    expr->output(level + 4);
}

void FunctionDef::output(int level) {
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine\tfunction name: %s\ttype: %s\n", level, ' ', name.c_str(), type.c_str());
    if (decl) {
        decl->output(level + 4);
    }
    stmt->output(level + 4);
}